# -*- coding: utf-8 -*-


language: python
python:
  - "2.7"
  - "3.5"

sudo: false

install:
  - pip install tox==2.3.1

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then tox -e py35; fi
