# -*- coding: utf-8 -*-


import os
import testfixtures


def before_scenario(context, scenario):
    """Prepare a fresh environment for each scenario."""

    # Prepare a new temporary directory.
    context.directory = testfixtures.TempDirectory(create=True)
    context.old_cwd = os.getcwd()
    context.new_cwd = context.directory.path

    # Move into our new working directory.
    os.chdir(context.new_cwd)


def after_scenario(context, scenario):
    """Leave the environment fresh after each scenario."""

    # Move back into the original working directory.
    os.chdir(context.old_cwd)

    # Delete all content generated by the test.
    context.directory.cleanup()
